apiVersion: apps/v1

kind: Deployment

metadata:

  name: nodejsapp

spec:

  replicas: 2

  selector:

    matchLabels:

      app: nodejsapp

  template:

    metadata:

      labels:

        app: nodejsapp

    spec:

      containers:

        - name: nodejsapp

          image: ltim01.azurecr.io/nodejsapp:latest

          ports:

            - containerPort: 3000
