apiVersion: v1

kind: Service

metadata:

  name: nodejsapp-service

spec:

  type: LoadBalancer

  selector:

    app: nodejsapp

  ports:

    - port: 80

      targetPort: 3000

      nodePort: 30080
